language: python

python: "3.6"

install:
  - pip install -r requirements.txt

script:
  - python openapimixer.py

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  on:
    branch: master
