type: object
description: A HTTP action.
required:
  - url
properties:
  description:
    description: Human readable description for this action.
    type: string
  verb:
    description: HTTP verb
    type: string
    enum:
      - head
      - get
      - post
      - patch
      - put
      - delete
    default: put
  payload:
    description: HTTP call payload
    type: object
  url:
      type: string
      format: url
example:
  {
    "verb": "put",
    "payload": {"action": "stop"},
    "url": "https://api.pollination.cloud/simulations/1234-5678-910/actions"
  }  
