type: object
description: Pollination workflow schema
required:
  - type
  - name
  - simulations
properties:
  type:
    type: string
    enum:
      - 'Workflow'
  name:
    $ref: "#/components/schemas/ValidString"
  spec:
    type: object
    description: Workflow specifications.
    readOnly: true
    properties:
      parallelism:
        description: |
          Parallelism limits the max total parallel pods that can execute at the same
          time in a workflow
        type: integer
  simulations:
    description: List of workflow simulations
    type: array
    items:
      oneOf:
        - $ref: "#/components/schemas/DaylightFactor"
        - $ref: "#/components/schemas/PointInTime"
  actions:
    description: List of available actions for workflow.
    type: array
    readOnly: true
    items:
      $ref: "#/components/schemas/Action"
  status:
    $ref: "#/components/schemas/WorkflowStatus"
